source 'https://rubygems.org'

ruby '2.3.3'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'activerecord-postgis-adapter', '>= 6.0.0'
gem 'devise_token_auth', '>= 1.1.5'
gem 'faker'
gem 'jbuilder', '>= 2.6.4'
gem 'pg'
gem 'puma', '>= 4.3.12'
gem 'rack-cors', '>= 1.0.5'
gem 'rails', '>= 6.1.7.3'
gem 'rgeo'
gem 'rolify'
gem 'swagger-blocks'
gem 'twilio-ruby'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'dotenv-rails', '>= 2.7.6'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'rubocop', '>= 0.49.0', require: false
end

group :test do
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'webmock'
end

group :development do
  gem 'listen'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
